{
  "context": "Final Generate Failure after all retries",
  "datetime": "2025-03-31T04:56:07.630867",
  "stack_trace": "NoneType: None\n",
  "exception": "ERROR: Failed to get a valid response after 2 attempts."
}